FROM nginx

COPY index.html /usr/share/nginx/html/index.html
COPY vue.min.js /usr/share/nginx/html/vue.min.js
COPY nginx.conf /etc/nginx/nginx.conf
COPY starter.sh /etc/nginx/starter.sh

EXPOSE 80

CMD ["/bin/sh", "/etc/nginx/starter.sh"]
